# Generated by Django 6.0.1 on 2026-01-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='roles',
            field=models.TextField(max_length=150),
        ),
    ]
